### PR TITLE
tracing configmap added

### PR DESCRIPTION
**Pull request by Shashankft9**
Fixes 
Added a tracing configmap, so that the configAccessor in ReconcileKind can pick it up and expose traces on jaeger/zipkin like other sources. 

## Proposed Changes

- Adds a configmap yaml in `config` during installation

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by evankanderson — COMMENTED** [review]
/hold

/assign @lionelvillard 

This seems reasonable on its face, but I'm guessing that `knative-sources` is a namespace shared across a number of components. I'm not sure how we're handling shared configs in that namespace (particularly if different sources wanted different tracing configurations).

**Comment by lionelvillard** [comment]
There is no written down conventions about where to deploy sources and how to share configmaps. The "trend" has been to install sources in `knative-eventing`, sharing configmaps with the other components.

**Comment by matzew** [comment]
related https://github.com/knative-sandbox/eventing-ceph/issues/195

**Pull request closed without merging**
